Run instrumented tests on iPad (#2575)
Fixes https://youtrack.jetbrains.com/issue/CMP-8792/Run-tests-on-iPad

## Release Notes
N/A

diff --git a/.github/workflows/compose-tests.yml b/.github/workflows/compose-tests.yml
--- a/.github/workflows/compose-tests.yml
+++ b/.github/workflows/compose-tests.yml
@@ -104,7 +104,11 @@ jobs:
 
   compose-ios-instrumented-tests:
     runs-on: macos-15-xlarge
-    name: Compose iOS Instrumented Tests
+    strategy:
+      fail-fast: false
+      matrix:
+        device: [ 'iPhone 16', 'iPad Pro 11-inch (M4)' ]
+    name: Compose iOS Instrumented Tests ${{ matrix.device }}
     env:
       GRADLE_OPTS: -Xmx12g -Dorg.gradle.daemon=false
     steps:
@@ -117,12 +121,44 @@ jobs:
       - name: Setup Xcode
         uses: ./.github/actions/setup-xcode
 
+      - name: Get iOS Simulator UDID
+        id: get-simulator-udid
+        shell: bash
+        run: |
+          DEVICE_NAME="${{ matrix.device }}"
+          DEVICE_VERSION="18.6"
+          
+          DEVICE_DASH="${DEVICE_VERSION//./-}"   # 16.0 -> 16-0
+          
+          echo "Looking for device: '$DEVICE_NAME' ($DEVICE_VERSION)"
+          
+          SIMULATOR_ID=$(xcrun simctl list devices available -j \
+          | jq -r --arg device "$DEVICE_NAME" --arg vdot "$DEVICE_VERSION" --arg vdash "$DEVICE_DASH" '
+          .devices
+          | to_entries[]
+          | select(.key | (contains($vdot) or contains($vdash)))
+          | .value[]
+          | select(.name == $device)
+          | .udid
+          ' | head -n 1)
+          
+          if [ -z "$SIMULATOR_ID" ]; then
+          echo "Simulator not found for $DEVICE_NAME ($DEVICE_VERSION)"
+          echo "Available runtimes and matching devices:"
+          xcrun simctl list devices available -j | jq -r '
+          .devices | to_entries[] | "\(.key):\n  " + ( [.value[] | "\(.name) \(.udid) \(.state)"] | join("\n  ") )
+          '
+          exit 1
+          fi
+          
+          echo "Found simulator ID: $SIMULATOR_ID"
+
+          # make available to later steps
+          echo "simulator-id=$SIMULATOR_ID" >> "$GITHUB_OUTPUT"
+
       - name: Configure Simulator
         run: |
-          xcrun simctl list devices
-
-          # Boot a test simulator
-          xcrun simctl boot "iPhone 16"
+          xcrun simctl boot "${{ steps.get-simulator-udid.outputs.simulator-id }}"
 
           # Write the accessibility flags inside the Simulator:
           xcrun simctl spawn booted defaults write com.apple.Accessibility AccessibilityEnabled -bool true
@@ -141,7 +177,7 @@ jobs:
           xcodebuild test \
             -scheme Launcher \
             -project Launcher.xcodeproj \
-            -destination 'platform=iOS Simulator,name=iPhone 16'
+            -destination 'platform=iOS Simulator,id=${{ steps.get-simulator-udid.outputs.simulator-id }}'
 
       - name: Test Summary
         uses: test-summary/action@v2
